### ISSUE TITLE
Duping items with Keepinventory Enabled

### ISSUE THREAD

**Issue by Phonavis** [TehNut-Mods/SimpleGraves#1]
Seriously, it's in the title.

With Keep Inventory enabled, it still spawns a grave, with all the items you had.
Except you already had them, cause you had Keep inventory.

See the issue?

**Comment by TehNut** [comment]
Seriously, it's common sense.

Usually you're supposed to report bugs while not sounding like a dick.

See the issue?

**Comment by Phonavis** [comment]
I.. wasn't attempting to...
But ok thanks...
