### ISSUE TITLE
Not spawning

### ISSUE THREAD

**Issue by Bellwar** [TehNut-Mods/SimpleGraves#2]
I had die in mine with full inventory aaaand the grave took all items but didnt spawn so I lost it everything. I doesnt do everytime this is first but just you know. Version 1.0.0.2

**Comment by TehNut** [comment]
Do you happen to remember if you were standing in any kind of block? IE: BoP flowers and similar

**Comment by Kumomo** [comment]
I had this happen to me on a singleplayer world I made recently. I was falling onto a pressure plate on top of a Neotech Grinder. Grinder is supposed to grind more based on fall distance and I thought my items were safe.

I tested it with just the pressure plate and the grave does not appear. Items poof.
V. 1.0.0.2

**Comment by TehNut** [comment]
Try with build 3/4 whenever they hit Curse

**Comment by Kumomo** [comment]
Both v1.0.0.3 and v1.0.0.5 seems to have fixed it for me. The grave spawns a few blocks away with all items.

Awesome quick response on that. ^^

**Comment by Bellwar** [comment]
Sorry for me not responding I was on holidays :) I hope it will be ok now. I think I died on normal stone but not sure if it didn't think I'm a little bit in a wall or something like that.

**Comment by TehNut** [comment]
No worries. I thought that was the issue and just wanted to confirm.

**Comment by kjj194** [comment]
I just had this happen on version 1.0.0-6 in The Pioneers modpack. Was standing on vanilla carpet. It is reproducible and if you have trouble making it happen I can provide a save.
