### ISSUE TITLE
Graves destroyed

### ISSUE THREAD

**Issue by Kashdeya** [TehNut-Mods/SimpleGraves#3]
The graves get destroyed and all the items in them when a creeper blows up. I am using the version for 1.9

**Comment by TehNut** [comment]
Is this only when you die? Or when a Creeper explodes near a Grave?

**Comment by Kashdeya** [comment]
ok we died to a creeper and no grave stone was left behind. we have not tried to see if a creeper can blow up a gravestone once it is placed.

**Comment by TehNut** [comment]
Project dropped
